### ISSUE TITLE
goapp.db这个文件乱码，请问是什么编码格式的utf-8不行

### ISSUE THREAD

**Issue by firelph** [it234/goapp#6]

**Comment by firelph** [comment]
goapp.db这个文件乱码，请问是什么编码格式的utf-8不行

**Comment by it234** [comment]
你好，你是用什么工具打开呢，这是splite3数据库

**Comment by zinwalin** [comment]
vscode里安装SQLite插件，然后Open Database，在左下角就能看到数据表。 点击红圈的按钮就可以在右侧看到表的数据 。

![image](https://user-images.githubusercontent.com/5416196/67152670-f2934780-f337-11e9-9d95-45aa0d95d196.png)
